package pojo;
// Generated Oct 13, 2022 12:13:04 PM by Hibernate Tools 4.3.1

import DAO.DAOAdmin;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblAdmin generated by hbm2java
 */
@ManagedBean
public class TblAdmin  implements java.io.Serializable {


     private Integer idAdmin;
     private String username;
     private String password;
     
     public String login_admin()
     {
         DAOAdmin uDao = new DAOAdmin();
         List<TblAdmin> us = uDao.getBY(username, password);
         try {    
          if(us != null)
         {
             username = us.get(0).username;
             password = us.get(0).password;
             return "admin";       
         } 
         } catch (Exception e) {
             System.out.println(e);
         }
         return "gagaladmin";
     }

    public TblAdmin() {
    }

    public TblAdmin(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


