package pojo;
// Generated Oct 13, 2022 12:39:03 AM by Hibernate Tools 4.3.1


import DAO.DAOorder;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblOrder generated by hbm2java
 */
@ManagedBean
public class TblOrder  implements java.io.Serializable {


     private Integer noOrder;
     private String namaMenu;
     private String jumlahOrder;
     private String harga;
     private String total;
     
     
      public void save_order()
     {
         DAOorder add = new DAOorder();
         add.add_order(this);
     }
      public List<TblOrder> getAllRecords()
    {
        DAOorder odr = new DAOorder();
        List<TblOrder> lOdr = odr.retrieveTblOrder();
        return lOdr;          
    }
      public String getByIdOrder()
    {
        String no_order = noOrder.toString();
        DAOorder odr = new DAOorder();
        List<TblOrder> lodr = odr.getbyID(no_order);
        try {
            if (lodr != null){
        namaMenu = lodr.get(0).getNamaMenu();
        jumlahOrder =lodr.get(0).getJumlahOrder();
        harga= lodr.get(0).getHarga();
        total = lodr.get(0).getTotal();
        return "admin";
        }
            
        } catch (Exception e) {
            System.out.println(e);
        }
      
   
        return"admin";
    }
    public String editorder(){
        DAOorder odr = new DAOorder();
        odr.editOrder(this);
        jumlahOrder = "";
        jumlahOrder= "";
        harga= "";
        total= "";

        return "admin";
    }
    
    
    public String deleteorder(){
        DAOorder odr = new DAOorder();
        odr.deleteOrder(noOrder);
        namaMenu = "";
        jumlahOrder = "";
        harga= "";
        total = "";
        return "admin";
    }
    
    public String resetorder(){
        DAOorder odr = new DAOorder();
        odr.resetOrder(this);
        namaMenu= "";
        jumlahOrder = "";
        harga = "";
        total= "";
        return "admin";
    }
    
    public TblOrder() {
    }

    public TblOrder(String namaMenu, String jumlahOrder, String harga, String total) {
       this.namaMenu = namaMenu;
       this.jumlahOrder = jumlahOrder;
       this.harga = harga;
       this.total = total;
    }
   
    public Integer getNoOrder() {
        return this.noOrder;
    }
    
    public void setNoOrder(Integer noOrder) {
        this.noOrder = noOrder;
    }
    public String getNamaMenu() {
        return this.namaMenu;
    }
    
    public void setNamaMenu(String namaMenu) {
        this.namaMenu = namaMenu;
    }
    public String getJumlahOrder() {
        return this.jumlahOrder;
    }
    
    public void setJumlahOrder(String jumlahOrder) {
        this.jumlahOrder = jumlahOrder;
    }
    public String getHarga() {
        return this.harga;
    }
    
    public void setHarga(String harga) {
        this.harga = harga;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }




}


