package pojo;
// Generated Oct 13, 2022 12:39:03 AM by Hibernate Tools 4.3.1

import DAO.DAOLogin;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblUser generated by hbm2java
 */
@ManagedBean
public class TblUser  implements java.io.Serializable {


     private Integer idUser;
     private String username;
     private String password;
     
      public void save_user()
     {
         DAOLogin add = new DAOLogin();
         add.add_user(this);
     }
           
public String login_user()
     {
         DAOLogin uDao = new DAOLogin();
         List<TblUser> us = uDao.getBY(username, password);
         try {    
          if(us != null)
         {
             username = us.get(0).username;
             password = us.get(0).password;
             return "index";       
         } 
         } catch (Exception e) {
             System.out.println(e);
         }
         return "gagallogin";
     }

   
    public TblUser() {
    }

    public TblUser(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


